### ISSUE TITLE
installer freeze when using UEFI with increased resolution

### ISSUE THREAD

**Issue by MrM40** [opnsense/bsdinstaller#16]
First off all, is this the right place to report a bug with the OPNsense installer?
OPNsense version: 19.1 (DVD iso)
Host: KVM/QEMU

If I increase the UEFI resolution to 1024*768 the installer freeze in the second window "Select Task"
![uefi_error](https://user-images.githubusercontent.com/16258063/52178892-e714e600-27d3-11e9-99cd-e8434d2036b8.jpg)

using default 640x480 it works fine:
![uefi_ok](https://user-images.githubusercontent.com/16258063/52178906-0b70c280-27d4-11e9-9db3-fa0c83def826.jpg)

**Comment by fichtner** [comment]
Hi,

This is the right place but I think that the installer needs to be replaced completely as it was written in a time where resizing didn't exist... I would hope to get this done by 19.7 but it is a lot of work.


Cheers,
Franco

**Comment by fichtner** [comment]
We're moving to a new installer... https://github.com/opnsense/installer/issues/1
