### ISSUE TITLE
Hyper-V Gen2 VM fails install

### ISSUE THREAD

**Issue by Solaris17** [opnsense/bsdinstaller#19]
Hello,

The installation of 20.7 (DVD  ISO) will not proceed at the install menu on a generation 2 hyper-v VM.

The VM is configured with Secure boot disabled as it will not boot off of the CD with any of the options including the normally used UEFI certificate authority.

![image](https://user-images.githubusercontent.com/2453047/89545599-910e6d80-d7d1-11ea-932d-1ea9937292b0.png)

The install proceeds as normal until you come across the install type menu. At which point the keyboard stop responding.

![image](https://user-images.githubusercontent.com/2453047/89545576-894ec900-d7d1-11ea-8584-86359468324c.png)

The install cannot continue at this point and even disconnecting from console and reconnecting will not fix it.

However, if the install is done on a gen1 VM the install will proceed without issue. 

After the install during which EFI/GPT is selected you can then create a Gen2 VM and attach the VHD and it will boot.

**Comment by flo-mic** [comment]
I had the same issue. For me the following workaround worked:
Start the VM with the installer medium. Connect with ssh to the host with the installer user. Do not use the host console for the installation. Then run the setup dialog. It will not freeze anymore on this step.

**Comment by nighty2k7** [comment]
Still an issue in 21.1. Workaround still applies!

**Comment by fichtner** [comment]
Duplicates https://github.com/opnsense/installer/issues/1
