### ISSUE TITLE
Installer issues

### ISSUE THREAD

**Issue by petererdos** [opnsense/bsdinstaller#21]
I can't really provide logs for this, so I'll try to explain what happens.

Sources for this reporting:
1. https://forum.opnsense.org/index.php?topic=7547
2. This is not exactly the same as p1, but similar hardware and exactly the same outcome: https://forum.opnsense.org/index.php?topic=7329

I read many times what Franco was advising in similar cases, especially for p1, so I tried exactly that: install FreeBSD first and see if that works. And it did, FreeBSD installed quite nicely.

As you can see from the forum report, OPNsense 18.1 installer (amd64, vga) fails to install. It hangs right after formatting, right before partitioning the HDD.

I'll define what hang means here:
1. Any visible progress stops after the HDD is formatted 
2. I think when trying to partition the HDD, the installer hangs
3. There is no visible progress on the screen after this point
4. CTRL+ALT+DELETE or the power button will display some logs, overlaying the blue screen of the installer with the installation progress
5. There is absolutely nothing wrong hardware wise (professionally tested)

I'll have this hardware (from p1) for another 2 or 3 days, as it is not mine. It will be the main gateway of a client's network, deployed far away from where I live, so access will be difficult, the issue impossible to reproduce and confirm a fix once it's put in place. If anybody has the time to investigate before relocating the box, I'll try to be available.

Thank you all.

**Comment by marjohn56** [comment]
I believe it's very much on @fichtner's radar,

**Comment by fichtner** [comment]
Sure, work for https://github.com/opnsense/installer/issues/1 currently in progress in time for 21.7.
