### ISSUE TITLE
Installer continues anyway when passwords for root account don't match

### ISSUE THREAD

**Issue by bram-pkg** [opnsense/bsdinstaller#22]

**Comment by fichtner** [comment]
Are you sure? ;)

**Comment by bram-pkg** [comment]
Yeah, if you type in two passwords that are not the same and you press OK on that prompt, it will still finish the installation.

**Comment by fichtner** [comment]
Huh, the install is already finished and the password reset is optional anyway? I am unsure what you are reporting here and the lack of screenshots and reproduction steps is not helping.

**Comment by bram-pkg** [comment]
I'll make a VM and provide some screenshots.

**Comment by bram-pkg** [comment]
I have no clue why, but it seems to work now.
